backend:
  name: github
  repo: JuanC-JC/CamaraVerde
  branch: main

media_folder: static/assets
public_folder: /static/assets

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "index"
    media_folder: "assets"
    public_folder: "assets"
    path: "{{title}}/index"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Gallery",
          name: "galleryImages",
          widget: "list",
          field: { label: "Image", name: "image", widget: "image" },
        }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "noticias"
    label: "Noticias"
    folder: "content/noticias"
    create: true
    slug: "index"
    media_folder: "assets"
    public_folder: "assets"
    path: "{{title}}/index"
    editor:
      preview: false
    fields:
      - {
          label: "Convocatoria",
          name: "convocatoria",
          widget: "boolean",
          default: false,
        }
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha de publicación", name: "date", widget: "datetime" }

      - { label: "Imagen", name: "image", choose_url: false, widget: "image" }
      - { label: "Contenido", name: "content", widget: "text" }

  - name: "experiencia"
    label: "Experiencia"
    folder: "content/experiencia"
    create: true
    slug: "index"
    media_folder: "assets"
    public_folder: "assets"
    path: "{{title}}/index"
    editor:
      preview: false
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha de publicación", name: "date", widget: "datetime" }
      - { label: "Contenido", name: "content", widget: "text" }
      - {
          label: "Imagenes",
          name: "galleryImages",
          widget: "list",
          min: 3,
          max: 6,
          field:
            {
              label: "Imagen",
              name: "image",
              choose_url: false,
              widget: "image",
            },
        }
      - label: "Equipo de trabajo"
        name: "team"
        widget: "list"
        min: 3
        max: 5
        fields:
          - { label: "Nombre", name: "name", widget: "string" }
          - { label: "Cargo", name: "job", widget: "string" }
