backend:
  name: github
  repo: JuanC-JC/CamaraVerde
  branch: main

media_folder: static/assets
public_folder: static/assets

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"cle
    create: true
    slug: "index"
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Main Image", name: "mainImg", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
