backend:
  name: github
  repo: JuanC-JC/CamaraVerde
  branch: main

media_folder: static/assets
public_folder: /static/assets

collections:
  - name: "noticias"
    label: "Noticias"
    folder: "content/noticias"
    create: true
    slug: "index"
    media_folder: "assets"
    public_folder: "assets"
    path: "{{title}}/index"
    editor:
      preview: false
    fields:
      - {
          label: "Convocatoria",
          name: "convocatoria",
          widget: "boolean",
          default: false,
        }
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha de publicación", name: "date", widget: "datetime" }

      - { label: "Imagen", name: "image", choose_url: false, widget: "image" }
      - { label: "Contenido", name: "content", widget: "string" }
      - label: "Autor de publicación"
        name: "post"
        widget: "object"
        fields:
          - { label: "Autor", name: "name", widget: "string" }
          - {
              label: "Link de la publicación",
              name: "link",
              widget: "string",
              required: false,
            }

  - name: "experiencia"
    label: "Experiencia"
    folder: "content/experiencias"
    create: true
    slug: "index"
    media_folder: "assets"
    public_folder: "assets"
    path: "{{title}}/index"
    editor:
      preview: false
    fields:
      - { label: "Título", name: "title", widget: "string" }

      - label: "Fechas de la experiencia"
        name: "dateRange"
        widget: "object"
        fields:
          - { label: "Fecha de Inicio", name: "init", widget: "datetime" }
          - {
              label: "Fecha de Finalización",
              name: "finish",
              default: "",
              widget: "datetime",
              required: false,
            }

      - { label: "Contenido", name: "content", widget: "string" }
      - {
          label: "Imagenes",
          name: "galleryImages",
          widget: "list",
          min: 2,
          max: 6,
          field:
            {
              label: "Imagen",
              name: "image",
              choose_url: false,
              widget: "image",
            },
        }
      - label: "Equipo de trabajo"
        name: "team"
        widget: "list"
        min: 3
        max: 5
        fields:
          - { label: "Nombre", name: "name", widget: "string" }
          - { label: "Cargo", name: "job", widget: "string" }

      - { label: "Actividades", name: "activities", widget: "string" }
      - {
          label: "Socios - Aliados",
          name: "galleryPartners",
          widget: "list",
          min: 1,
          max: 6,
          field:
            {
              label: "Imagen",
              name: "image",
              choose_url: false,
              widget: "image",
            },
        }
